### ISSUE TITLE
This makes me very angry

### ISSUE THREAD

**Issue by Baddaboo** [jkingsman/HDL#1]
This library causes an extremely triggering distortions that make for a poor user experience. 10/10 would not recommend 😡
![randscroll](https://cloud.githubusercontent.com/assets/3477362/22126049/f89cdefc-de4a-11e6-8fbd-44f443874937.gif)

**Comment by jkingsman** [comment]
Hahaha how did you even find this? And sorry it triggers you. Maybe you shouldn't use libraries targeted towards disrupting humans on yourself.
